# Generated by Django 3.2.2 on 2021-05-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('duration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeStamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeStamp', to='PresenceSummarizer.result')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='timeStamps',
            field=models.ManyToManyField(to='PresenceSummarizer.TimeStamps'),
        ),
    ]
